using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Threading;
using ICSharpCode.AvalonEdit.CodeCompletion;
using Probe.DbEditor.Models;
using Probe.DbEditor.Services;
using Probe.DbEditor.Views.SqlEditor;

namespace Probe.DbEditor.Views;

public partial class SessionView : UserControl
{
    private const int GridAppendBatchSize = 20;
    private static readonly Brush EditingTextBackground = new SolidColorBrush(Color.FromRgb(226, 223, 208));
    private static readonly Brush EditingTextForeground = new SolidColorBrush(Color.FromRgb(47, 32, 45));
    private static readonly Brush EditingTextBorder = new SolidColorBrush(Color.FromRgb(159, 95, 66));
    private static readonly Brush EditingTextSelection = new SolidColorBrush(Color.FromRgb(195, 132, 98));
    private readonly DatabaseSession _session;
    private readonly SqlCompletionService _completionService = new();
    private readonly ObservableCollection<PendingCellEdit> _pendingEdits = [];
    private static readonly Style EditingTextBoxStyle = CreateEditingTextBoxStyle();
    private TableDataResult? _currentTable;
    private CompletionWindow? _completionWindow;
    private string? _orderByColumn;
    private ListSortDirection? _orderDirection;
    private bool _loaded;
    private PendingEditCandidate? _pendingEditCandidate;
    private bool _isCapturingEdit;
    private bool _isUpdatingQueryEditor;
    private bool _queryTextEditedByUser;
    private bool _suppressSchemaSelectionChanged;
    private CancellationTokenSource? _tableLoadCancellation;
    private int _tableLoadVersion;
    private CancellationTokenSource? _queryCancellation;
    private int _queryRunVersion;
    private int _runningOperationCount;

    public SessionView(DatabaseSession session)
    {
        _session = session;
        InitializeComponent();
        SessionTitleText.Text = session.Profile.Name;
        PendingEditsGrid.ItemsSource = _pendingEdits;
        QueryLogGrid.ItemsSource = _session.QueryLog;
        ConfigureQueryEditor();
        _pendingEdits.CollectionChanged += (_, _) => UpdatePendingEditButtons();
        DeferEditsToggle.Checked += (_, _) => UpdatePendingEditButtons();
        DeferEditsToggle.Unchecked += (_, _) => UpdatePendingEditButtons();
        UpdatePendingEditButtons();
        UpdateTopBarOperationState();
        SetTableEmptyState(false);
    }

    public async ValueTask CloseAsync()
    {
        _tableLoadCancellation?.Cancel();
        _queryRunVersion++;
        _queryCancellation?.Cancel();
        await _session.DisposeAsync();
    }

    private async void SessionView_Loaded(object sender, RoutedEventArgs e)
    {
        if (_loaded)
        {
            return;
        }

        _loaded = true;
        await RefreshSchemasAsync();
    }

    private async void Refresh_Click(object sender, RoutedEventArgs e)
    {
        await RefreshSchemasAsync(reloadSelectedTable: true);
    }

    private async void SchemaTree_SelectedItemChanged(object sender, RoutedPropertyChangedEventArgs<object> e)
    {
        if (_suppressSchemaSelectionChanged)
        {
            return;
        }

        if (SchemaTree.SelectedItem is TreeViewItem { Tag: TreeNodeInfo { Kind: TreeNodeKind.Table } node })
        {
            await LoadTableAsync(node.SchemaName, node.TableName);
        }
    }

    private void TableDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        ConfigureAutoGeneratedColumn(e, BindingMode.TwoWay);
        if (string.Equals(e.PropertyName, _orderByColumn, StringComparison.OrdinalIgnoreCase))
        {
            e.Column.SortDirection = _orderDirection;
        }
    }

    private void ReadOnlyDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        ConfigureAutoGeneratedColumn(e, BindingMode.OneWay);
    }

    private static void ConfigureAutoGeneratedColumn(DataGridAutoGeneratingColumnEventArgs e, BindingMode bindingMode)
    {
        e.Column.Header = e.PropertyName;
        e.Column.SortMemberPath = e.PropertyName;

        if (e.Column is DataGridBoundColumn boundColumn)
        {
            boundColumn.Binding = new Binding($"[{e.PropertyName}]")
            {
                Mode = bindingMode,
                UpdateSourceTrigger = bindingMode == BindingMode.TwoWay
                    ? UpdateSourceTrigger.LostFocus
                    : UpdateSourceTrigger.Default,
                ValidatesOnExceptions = true
            };

            if (bindingMode == BindingMode.TwoWay && boundColumn is DataGridTextColumn textColumn)
            {
                textColumn.EditingElementStyle = EditingTextBoxStyle;
            }
        }
    }

    private async void TableDataGrid_Sorting(object sender, DataGridSortingEventArgs e)
    {
        if (_currentTable is null)
        {
            return;
        }

        var columnName = e.Column.SortMemberPath;
        if (string.IsNullOrWhiteSpace(columnName))
        {
            return;
        }

        e.Handled = true;
        var direction = e.Column.SortDirection == ListSortDirection.Ascending
            ? ListSortDirection.Descending
            : ListSortDirection.Ascending;

        await LoadTableAsync(_currentTable.SchemaName, _currentTable.TableName, columnName, direction);
    }

    private void TableDataGrid_CellEditEnding(object sender, DataGridCellEditEndingEventArgs e)
    {
        if (e.EditAction != DataGridEditAction.Commit || _currentTable is null)
        {
            return;
        }

        var columnName = Convert.ToString(e.Column.Header);
        if (string.IsNullOrWhiteSpace(columnName) || e.Row.Item is not DataRowView rowView)
        {
            return;
        }

        if (e.EditingElement is FrameworkElement editingElement)
        {
            UpdateEditingElementSource(editingElement);
        }

        _pendingEditCandidate = new PendingEditCandidate(rowView.Row, columnName);
    }

    private void TableDataGrid_PreparingCellForEdit(object sender, DataGridPreparingCellForEditEventArgs e)
    {
        if (e.EditingElement is not TextBox textBox)
        {
            return;
        }

        ApplyEditingTextBoxVisuals(textBox);
        textBox.Dispatcher.BeginInvoke(() => ApplyEditingTextBoxVisuals(textBox), DispatcherPriority.Loaded);
    }

    private async void TableDataGrid_CurrentCellChanged(object sender, EventArgs e)
    {
        if (_isCapturingEdit || _pendingEditCandidate is null)
        {
            return;
        }

        var candidate = _pendingEditCandidate;
        _pendingEditCandidate = null;
        _isCapturingEdit = true;
        try
        {
            await Dispatcher.InvokeAsync(() => { }, DispatcherPriority.Background);
            await CaptureCellEditAsync(candidate.Row, candidate.ColumnName);
        }
        finally
        {
            _isCapturingEdit = false;
        }
    }

    private async void ApplyPending_Click(object sender, RoutedEventArgs e)
    {
        await ApplyPendingEditsAsync();
    }

    private void RevertPending_Click(object sender, RoutedEventArgs e)
    {
        if (!CanReviewPendingEdits())
        {
            SetStatus("No pending edits to revert.");
            return;
        }

        foreach (var row in _pendingEdits.Select(edit => edit.Row).Distinct().ToList())
        {
            row.RejectChanges();
        }

        _pendingEdits.Clear();
        SetStatus("Pending edits reverted.");
    }

    private async void CreateIndex_Click(object sender, RoutedEventArgs e)
    {
        if (_currentTable is null)
        {
            SetStatus("Select a table first.");
            return;
        }

        try
        {
            using var running = BeginRunningOperation();
            var columns = IndexColumnsTextBox.Text
                .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .ToList();
            await _session.CreateIndexAsync(
                _currentTable.SchemaName,
                _currentTable.TableName,
                IndexNameTextBox.Text.Trim(),
                UniqueIndexCheckBox.IsChecked == true,
                columns);
            await LoadIndexesAsync(_currentTable.SchemaName, _currentTable.TableName);
            SetStatus("Index created.");
        }
        catch (Exception ex)
        {
            SetStatus(ex.Message);
        }
    }

    private async void DropIndex_Click(object sender, RoutedEventArgs e)
    {
        if (_currentTable is null || IndexesGrid.SelectedItem is not IndexInfo index)
        {
            SetStatus("Select an index first.");
            return;
        }

        try
        {
            using var running = BeginRunningOperation();
            await _session.DropIndexAsync(_currentTable.SchemaName, _currentTable.TableName, index.IndexName);
            await LoadIndexesAsync(_currentTable.SchemaName, _currentTable.TableName);
            SetStatus("Index dropped.");
        }
        catch (Exception ex)
        {
            SetStatus(ex.Message);
        }
    }

    private async void RunQuery_Click(object sender, RoutedEventArgs e)
    {
        if (_queryCancellation is not null)
        {
            return;
        }

        var cancellation = new CancellationTokenSource();
        _queryCancellation = cancellation;
        var queryVersion = ++_queryRunVersion;
        SetQueryRunning(true);
        using var running = BeginRunningOperation();

        try
        {
            QueryStatusText.Text = "Running...";
            await Dispatcher.Yield(DispatcherPriority.Background);
            var result = await _session.RunSqlAsync(QueryEditor.Text, cancellation.Token);
            if (!IsCurrentQueryRun(queryVersion, cancellation))
            {
                if (cancellation.IsCancellationRequested)
                {
                    QueryStatusText.Text = "Query stopped.";
                }

                return;
            }

            QueryResultGrid.ItemsSource = result.Rows.DefaultView;
            QueryStatusText.Text = result.Rows.Rows.Count > 0
                ? $"{result.Rows.Rows.Count} row(s)"
                : $"{result.RowsAffected} affected row(s)";
        }
        catch (OperationCanceledException) when (cancellation.IsCancellationRequested)
        {
            QueryStatusText.Text = "Query stopped.";
        }
        catch (Exception ex)
        {
            if (!IsCurrentQueryRun(queryVersion, cancellation) || cancellation.IsCancellationRequested)
            {
                QueryStatusText.Text = "Query stopped.";
                return;
            }

            QueryStatusText.Text = ex.Message;
        }
        finally
        {
            ClearTopBarResultSummary();
            if (ReferenceEquals(_queryCancellation, cancellation))
            {
                _queryCancellation = null;
            }

            SetQueryRunning(false);
            cancellation.Dispose();
        }
    }

    private void StopQuery_Click(object sender, RoutedEventArgs e)
    {
        if (_queryCancellation is null)
        {
            return;
        }

        QueryStatusText.Text = "Stopping...";
        _queryRunVersion++;
        _queryCancellation.Cancel();
    }

    private async Task RefreshSchemasAsync(bool reloadSelectedTable = false)
    {
        using var running = BeginRunningOperation();
        var tableToReload = reloadSelectedTable ? CaptureSelectedTableForRefresh() : null;

        try
        {
            SetStatus("Loading schemas...");
            SchemaTree.Items.Clear();
            var schemas = await _session.LoadSchemasAsync();
            TreeViewItem? tableItemToReselect = null;
            foreach (var schema in schemas)
            {
                var matchesReloadSchema = tableToReload is not null &&
                    string.Equals(schema, tableToReload.SchemaName, StringComparison.OrdinalIgnoreCase);
                var schemaItem = new TreeViewItem
                {
                    Header = schema,
                    Tag = new TreeNodeInfo(TreeNodeKind.Schema, schema, ""),
                    IsExpanded = IsDefaultSchema(schema) || matchesReloadSchema
                };

                _completionService.AddSchema(schema);
                var tables = await _session.LoadTablesAsync(schema);
                foreach (var table in tables)
                {
                    _completionService.AddTable(schema, table);
                    var tableItem = new TreeViewItem
                    {
                        Header = table,
                        Tag = new TreeNodeInfo(TreeNodeKind.Table, schema, table)
                    };
                    if (matchesReloadSchema &&
                        string.Equals(table, tableToReload!.TableName, StringComparison.OrdinalIgnoreCase))
                    {
                        tableItemToReselect = tableItem;
                    }

                    schemaItem.Items.Add(tableItem);
                }

                SchemaTree.Items.Add(schemaItem);
            }

            SetStatus($"Loaded {schemas.Count} schema(s).");
            if (tableToReload is null)
            {
                return;
            }

            if (tableItemToReselect is null)
            {
                SetStatus($"Loaded {schemas.Count} schema(s). Previously selected table no longer exists.");
                return;
            }

            SelectSchemaTreeItem(tableItemToReselect);
            await LoadTableAsync(
                tableToReload.SchemaName,
                tableToReload.TableName,
                tableToReload.OrderByColumn,
                tableToReload.OrderDirection);
        }
        catch (Exception ex)
        {
            SetStatus(ex.Message);
        }
    }

    private RefreshTableSelection? CaptureSelectedTableForRefresh()
    {
        if (SchemaTree.SelectedItem is TreeViewItem { Tag: TreeNodeInfo { Kind: TreeNodeKind.Table } node })
        {
            return new RefreshTableSelection(
                node.SchemaName,
                node.TableName,
                _orderByColumn,
                _orderDirection);
        }

        return _currentTable is null
            ? null
            : new RefreshTableSelection(
                _currentTable.SchemaName,
                _currentTable.TableName,
                _orderByColumn,
                _orderDirection);
    }

    private void SelectSchemaTreeItem(TreeViewItem item)
    {
        _suppressSchemaSelectionChanged = true;
        try
        {
            item.IsSelected = true;
            item.BringIntoView();
        }
        finally
        {
            _suppressSchemaSelectionChanged = false;
        }
    }

    private async Task LoadTableAsync(
        string schemaName,
        string tableName,
        string? orderByColumn = null,
        ListSortDirection? orderDirection = null)
    {
        var cancellation = BeginTableLoad();
        var loadVersion = _tableLoadVersion;
        var limit = ParseLimit();
        using var running = BeginRunningOperation();

        try
        {
            SetStatus($"Loading {schemaName}.{tableName}...");
            _orderByColumn = orderByColumn;
            _orderDirection = orderDirection;
            _currentTable = null;
            TableDataGrid.ItemsSource = null;
            SetTableEmptyState(false);
            ContentTab.Header = tableName;
            WorkspaceTabs.SelectedItem = ContentTab;
            await Dispatcher.Yield(DispatcherPriority.Background);

            var firstChunk = true;
            await foreach (var chunk in _session.StreamTableAsync(
                               schemaName,
                               tableName,
                               limit,
                               orderByColumn,
                               orderDirection,
                               cancellation.Token))
            {
                if (!IsCurrentTableLoad(loadVersion, cancellation))
                {
                    return;
                }

                if (firstChunk)
                {
                    _currentTable = CreateCurrentTable(chunk);
                    TableDataGrid.ItemsSource = _currentTable.Rows.DefaultView;
                    AddCurrentTableColumnsToCompletion();
                    PrepopulateQueryEditorIfPristine(_currentTable.SelectSql + ";");
                    firstChunk = false;
                }

                if (_currentTable is null)
                {
                    return;
                }

                await AppendChunkRowsAsync(_currentTable.Rows, chunk.Rows, loadVersion, cancellation);
                if (!IsCurrentTableLoad(loadVersion, cancellation))
                {
                    return;
                }

                SetStatus($"Loaded {_currentTable.Rows.Rows.Count} of up to {limit} row(s)...");
                await Dispatcher.Yield(DispatcherPriority.Background);
            }

            if (!IsCurrentTableLoad(loadVersion, cancellation) || _currentTable is null)
            {
                return;
            }

            var indexes = await _session.LoadIndexesAsync(schemaName, tableName, cancellation.Token);
            if (!IsCurrentTableLoad(loadVersion, cancellation))
            {
                return;
            }

            IndexesGrid.ItemsSource = indexes;
            var columns = await _session.LoadColumnDetailsAsync(schemaName, tableName, cancellation.Token);
            if (!IsCurrentTableLoad(loadVersion, cancellation))
            {
                return;
            }

            OverviewColumnsGrid.ItemsSource = columns;

            var editState = _currentTable.PrimaryKeyColumns.Count == 0
                ? "no primary key; editing disabled"
                : $"primary key: {string.Join(", ", _currentTable.PrimaryKeyColumns)}";
            SetTableEmptyState(_currentTable.Rows.Rows.Count == 0);
            SetTopBarReturnedRows(_currentTable.Rows.Rows.Count);
            SetStatus($"Loaded {_currentTable.Rows.Rows.Count} row(s), {editState}.");
        }
        catch (OperationCanceledException) when (cancellation.IsCancellationRequested)
        {
            if (IsCurrentTableLoad(loadVersion, cancellation))
            {
                SetTableEmptyState(false);
                SetStatus("Table load stopped.");
            }
        }
        catch (Exception ex)
        {
            if (IsCurrentTableLoad(loadVersion, cancellation))
            {
                SetTableEmptyState(false);
                SetStatus(ex.Message);
            }
        }
        finally
        {
            CompleteTableLoad(cancellation);
        }
    }

    private async Task LoadIndexesAsync(string schemaName, string tableName)
    {
        IndexesGrid.ItemsSource = await _session.LoadIndexesAsync(schemaName, tableName);
    }

    private async Task CaptureCellEditAsync(DataRow row, string columnName)
    {
        if (_currentTable is null || row.RowState == DataRowState.Unchanged)
        {
            return;
        }

        if (_currentTable.PrimaryKeyColumns.Count == 0)
        {
            row.RejectChanges();
            SetStatus("Cannot edit rows for tables without a primary key.");
            return;
        }

        var oldValue = NormalizeDbValue(row[columnName, DataRowVersion.Original]);
        var newValue = NormalizeDbValue(row[columnName, DataRowVersion.Current]);
        if (ValuesEqual(oldValue, newValue))
        {
            RemovePendingEdit(row, columnName);
            return;
        }

        var keyValues = _currentTable.PrimaryKeyColumns.ToDictionary(
            key => key,
            key => NormalizeDbValue(row[key, DataRowVersion.Original]));

        var edit = new PendingCellEdit(
            row,
            _currentTable.SchemaName,
            _currentTable.TableName,
            columnName,
            oldValue,
            newValue,
            keyValues);

        if (DeferEditsToggle.IsChecked == true)
        {
            QueuePendingEdit(edit);
            SetStatus("Edit queued for review.");
            return;
        }

        try
        {
            using var running = BeginRunningOperation();
            var affected = await _session.ApplyCellUpdateAsync(edit);
            row.AcceptChanges();
            SetStatus($"Edit applied. {affected} row(s) affected.");
        }
        catch (Exception ex)
        {
            row.RejectChanges();
            SetStatus(ex.Message);
        }
    }

    private async Task ApplyPendingEditsAsync()
    {
        if (!CanReviewPendingEdits())
        {
            SetStatus("No pending edits.");
            return;
        }

        using var running = BeginRunningOperation();

        try
        {
            var applied = 0;
            foreach (var editGroup in _pendingEdits.GroupBy(edit => edit.Row).ToList())
            {
                foreach (var edit in editGroup)
                {
                    applied += await _session.ApplyCellUpdateAsync(edit);
                }

                editGroup.Key.AcceptChanges();
                foreach (var edit in editGroup.ToList())
                {
                    _pendingEdits.Remove(edit);
                }
            }

            SetStatus($"Applied edits. {applied} row(s) affected.");
        }
        catch (Exception ex)
        {
            SetStatus(ex.Message);
        }
    }

    private async Task LoadColumnOverviewAsync(string schemaName, string tableName)
    {
        OverviewColumnsGrid.ItemsSource = await _session.LoadColumnDetailsAsync(schemaName, tableName);
    }

    private int ParseLimit()
    {
        return int.TryParse(LimitTextBox.Text, out var limit) && limit > 0 ? limit : 500;
    }

    private CancellationTokenSource BeginTableLoad()
    {
        _tableLoadCancellation?.Cancel();
        var cancellation = new CancellationTokenSource();
        _tableLoadCancellation = cancellation;
        _tableLoadVersion++;
        return cancellation;
    }

    private bool IsCurrentTableLoad(int loadVersion, CancellationTokenSource cancellation)
    {
        return loadVersion == _tableLoadVersion &&
               ReferenceEquals(_tableLoadCancellation, cancellation) &&
               !cancellation.IsCancellationRequested;
    }

    private void CompleteTableLoad(CancellationTokenSource cancellation)
    {
        if (ReferenceEquals(_tableLoadCancellation, cancellation))
        {
            _tableLoadCancellation = null;
        }

        cancellation.Dispose();
    }

    private bool IsCurrentQueryRun(int queryVersion, CancellationTokenSource cancellation)
    {
        return queryVersion == _queryRunVersion &&
               ReferenceEquals(_queryCancellation, cancellation) &&
               !cancellation.IsCancellationRequested;
    }

    private static TableDataResult CreateCurrentTable(TableDataChunkResult chunk)
    {
        var rows = chunk.Rows.Clone();
        rows.TableName = chunk.TableName;
        return new TableDataResult(
            chunk.SchemaName,
            chunk.TableName,
            rows,
            chunk.PrimaryKeyColumns,
            chunk.SelectSql,
            chunk.OrderByColumn,
            chunk.OrderDirection);
    }

    private async Task AppendChunkRowsAsync(
        DataTable target,
        DataTable chunk,
        int loadVersion,
        CancellationTokenSource cancellation)
    {
        var batchCount = 0;
        foreach (DataRow row in chunk.Rows)
        {
            if (!IsCurrentTableLoad(loadVersion, cancellation))
            {
                return;
            }

            var appended = target.NewRow();
            appended.ItemArray = row.ItemArray;
            target.Rows.Add(appended);
            appended.AcceptChanges();
            batchCount++;

            if (batchCount < GridAppendBatchSize)
            {
                continue;
            }

            batchCount = 0;
            await Dispatcher.Yield(DispatcherPriority.Background);
        }
    }

    private void SetStatus(string message)
    {
        SessionStatusText.Text = message;
    }

    private void SetQueryRunning(bool isRunning)
    {
        RunQueryButton.IsEnabled = !isRunning;
        StopQueryButton.IsEnabled = isRunning;
    }

    private IDisposable BeginRunningOperation()
    {
        ClearTopBarResultSummary();
        _runningOperationCount++;
        UpdateTopBarOperationState();
        return new RunningOperation(this);
    }

    private void EndRunningOperation()
    {
        _runningOperationCount = Math.Max(0, _runningOperationCount - 1);
        UpdateTopBarOperationState();
    }

    private void UpdateTopBarOperationState()
    {
        var isRunning = _runningOperationCount > 0;
        GlobalRunningIndicator.Visibility = isRunning
            ? Visibility.Visible
            : Visibility.Collapsed;
        GlobalResultSummaryText.Visibility = !isRunning && !string.IsNullOrWhiteSpace(GlobalResultSummaryText.Text)
            ? Visibility.Visible
            : Visibility.Collapsed;
    }

    private void SetTopBarReturnedRows(int rowCount)
    {
        GlobalResultSummaryText.Text = rowCount == 1
            ? "1 row returned"
            : $"{rowCount:N0} rows returned";
        UpdateTopBarOperationState();
    }

    private void ClearTopBarResultSummary()
    {
        GlobalResultSummaryText.Text = "";
        UpdateTopBarOperationState();
    }

    private bool CanReviewPendingEdits()
    {
        return DeferEditsToggle.IsChecked == true && _pendingEdits.Count > 0;
    }

    private void UpdatePendingEditButtons()
    {
        var canReviewPendingEdits = CanReviewPendingEdits();
        ApplyEditsButton.IsEnabled = canReviewPendingEdits;
        RevertEditsButton.IsEnabled = canReviewPendingEdits;
    }

    private void SetTableEmptyState(bool isVisible)
    {
        ContentEmptyState.Visibility = isVisible ? Visibility.Visible : Visibility.Collapsed;
    }

    private void ConfigureQueryEditor()
    {
        QueryEditor.SyntaxHighlighting = MySqlSyntaxHighlighting.Load();
        QueryEditor.Options.ConvertTabsToSpaces = true;
        QueryEditor.Options.IndentationSize = 4;
        QueryEditor.TextArea.TextEntered += QueryEditor_TextEntered;
        QueryEditor.TextArea.TextEntering += QueryEditor_TextEntering;
        QueryEditor.PreviewKeyDown += QueryEditor_PreviewKeyDown;
        QueryEditor.TextChanged += QueryEditor_TextChanged;
    }

    private void QueryEditor_TextChanged(object? sender, EventArgs e)
    {
        if (!_isUpdatingQueryEditor)
        {
            _queryTextEditedByUser = true;
        }
    }

    private void QueryEditor_TextEntered(object? sender, TextCompositionEventArgs e)
    {
        if (string.IsNullOrEmpty(e.Text))
        {
            return;
        }

        var character = e.Text[0];
        if (character == '.' || character == '@' || character == ':' || char.IsLetterOrDigit(character))
        {
            ShowCompletionWindow();
        }
    }

    private void QueryEditor_TextEntering(object? sender, TextCompositionEventArgs e)
    {
        if (_completionWindow is null || string.IsNullOrEmpty(e.Text))
        {
            return;
        }

        if (!SqlCompletionService.IsCompletionCharacter(e.Text[0]))
        {
            _completionWindow.CompletionList.RequestInsertion(e);
        }
    }

    private void QueryEditor_PreviewKeyDown(object sender, KeyEventArgs e)
    {
        if (e.Key == Key.Tab)
        {
            if (_completionWindow is not null)
            {
                _completionWindow.CompletionList.RequestInsertion(e);
            }
            else
            {
                ShowCompletionWindow();
            }

            e.Handled = true;
            return;
        }

        if (e.Key == Key.Space && Keyboard.Modifiers.HasFlag(ModifierKeys.Control))
        {
            ShowCompletionWindow();
            e.Handled = true;
        }
    }

    private void ShowCompletionWindow()
    {
        _completionWindow?.Close();

        var startOffset = SqlCompletionService.GetCompletionStartOffset(QueryEditor.Document, QueryEditor.CaretOffset);
        var prefix = SqlCompletionService.GetPrefix(QueryEditor.Document, QueryEditor.CaretOffset);
        var completionData = _completionService.BuildCompletionData(prefix, QueryEditor.Text);
        if (completionData.Count == 0)
        {
            return;
        }

        _completionWindow = new CompletionWindow(QueryEditor.TextArea)
        {
            StartOffset = startOffset,
            EndOffset = QueryEditor.CaretOffset,
            MinWidth = 260,
            MaxHeight = 280
        };

        foreach (var completion in completionData)
        {
            _completionWindow.CompletionList.CompletionData.Add(completion);
        }

        _completionWindow.Closed += (_, _) => _completionWindow = null;
        _completionWindow.Show();
    }

    private void PrepopulateQueryEditorIfPristine(string sql)
    {
        if (_queryTextEditedByUser)
        {
            return;
        }

        _isUpdatingQueryEditor = true;
        try
        {
            QueryEditor.Text = sql;
            QueryEditor.CaretOffset = 0;
        }
        finally
        {
            _isUpdatingQueryEditor = false;
        }
    }

    private void AddCurrentTableColumnsToCompletion()
    {
        if (_currentTable is null)
        {
            return;
        }

        foreach (DataColumn column in _currentTable.Rows.Columns)
        {
            _completionService.AddColumn(_currentTable.TableName, column.ColumnName);
        }
    }

    private bool IsDefaultSchema(string schemaName)
    {
        return !string.IsNullOrWhiteSpace(_session.Profile.DefaultSchema) &&
               string.Equals(_session.Profile.DefaultSchema, schemaName, StringComparison.OrdinalIgnoreCase);
    }

    private void QueuePendingEdit(PendingCellEdit edit)
    {
        RemovePendingEdit(edit.Row, edit.ColumnName);
        _pendingEdits.Add(edit);
    }

    private void RemovePendingEdit(DataRow row, string columnName)
    {
        var existingEdits = _pendingEdits.Where(edit =>
            ReferenceEquals(edit.Row, row) &&
            string.Equals(edit.ColumnName, columnName, StringComparison.OrdinalIgnoreCase)).ToList();
        foreach (var existing in existingEdits)
        {
            _pendingEdits.Remove(existing);
        }
    }

    private static void UpdateEditingElementSource(FrameworkElement editingElement)
    {
        var binding = editingElement switch
        {
            TextBox textBox => textBox.GetBindingExpression(TextBox.TextProperty),
            CheckBox checkBox => checkBox.GetBindingExpression(ToggleButton.IsCheckedProperty),
            ComboBox comboBox => comboBox.GetBindingExpression(Selector.SelectedValueProperty)
                                 ?? comboBox.GetBindingExpression(ComboBox.TextProperty),
            _ => null
        };
        binding?.UpdateSource();
    }

    private static Style CreateEditingTextBoxStyle()
    {
        var style = new Style(typeof(TextBox));
        style.Setters.Add(new Setter(Control.BackgroundProperty, EditingTextBackground));
        style.Setters.Add(new Setter(Control.ForegroundProperty, EditingTextForeground));
        style.Setters.Add(new Setter(Control.BorderBrushProperty, EditingTextBorder));
        style.Setters.Add(new Setter(Control.BorderThicknessProperty, new Thickness(1)));
        style.Setters.Add(new Setter(Control.PaddingProperty, new Thickness(4, 2, 4, 2)));
        style.Setters.Add(new Setter(TextBox.CaretBrushProperty, EditingTextForeground));
        style.Setters.Add(new Setter(TextBoxBase.SelectionBrushProperty, EditingTextSelection));
        style.Setters.Add(new Setter(TextBoxBase.SelectionOpacityProperty, 0.55));
        style.Setters.Add(new Setter(Control.TemplateProperty, CreateEditingTextBoxTemplate()));
        style.Setters.Add(new EventSetter(UIElement.PreviewMouseLeftButtonDownEvent, new MouseButtonEventHandler(EditingTextBox_PreviewMouseLeftButtonDown)));
        return style;
    }

    private static ControlTemplate CreateEditingTextBoxTemplate()
    {
        var border = new FrameworkElementFactory(typeof(Border));
        border.SetValue(Border.BackgroundProperty, new TemplateBindingExtension(Control.BackgroundProperty));
        border.SetValue(Border.BorderBrushProperty, new TemplateBindingExtension(Control.BorderBrushProperty));
        border.SetValue(Border.BorderThicknessProperty, new TemplateBindingExtension(Control.BorderThicknessProperty));
        border.SetValue(Border.PaddingProperty, new TemplateBindingExtension(Control.PaddingProperty));

        var contentHost = new FrameworkElementFactory(typeof(ScrollViewer), "PART_ContentHost");
        contentHost.SetValue(ScrollViewer.BackgroundProperty, Brushes.Transparent);
        border.AppendChild(contentHost);

        return new ControlTemplate(typeof(TextBox))
        {
            VisualTree = border
        };
    }

    private static void ApplyEditingTextBoxVisuals(TextBox textBox)
    {
        textBox.Background = EditingTextBackground;
        textBox.Foreground = EditingTextForeground;
        textBox.BorderBrush = EditingTextBorder;
        textBox.BorderThickness = new Thickness(1);
        textBox.CaretBrush = EditingTextForeground;
        textBox.SelectionBrush = EditingTextSelection;
        textBox.SelectionOpacity = 0.55;
        textBox.Padding = new Thickness(4, 2, 4, 2);
    }

    private static void EditingTextBox_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
    {
        if (e.ClickCount < 3 || sender is not TextBox textBox)
        {
            return;
        }

        textBox.Focus();
        textBox.SelectAll();
        e.Handled = true;
    }

    private static object? NormalizeDbValue(object? value)
    {
        return value is DBNull ? null : value;
    }

    private static bool ValuesEqual(object? left, object? right)
    {
        if (left is byte[] leftBytes && right is byte[] rightBytes)
        {
            return leftBytes.SequenceEqual(rightBytes);
        }

        return Equals(left, right);
    }

    private sealed record TreeNodeInfo(TreeNodeKind Kind, string SchemaName, string TableName);

    private sealed record PendingEditCandidate(DataRow Row, string ColumnName);

    private sealed record RefreshTableSelection(
        string SchemaName,
        string TableName,
        string? OrderByColumn,
        ListSortDirection? OrderDirection);

    private sealed class RunningOperation : IDisposable
    {
        private readonly SessionView _owner;
        private bool _disposed;

        public RunningOperation(SessionView owner)
        {
            _owner = owner;
        }

        public void Dispose()
        {
            if (_disposed)
            {
                return;
            }

            _disposed = true;
            _owner.EndRunningOperation();
        }
    }

    private enum TreeNodeKind
    {
        Schema,
        Table
    }
}
